### ISSUE TITLE
Program Input

### ISSUE THREAD

**Issue by vritant24** [vritant24/cleave-html#1]
I was thinking more of creating a setup file to allow multiple html files as input, because people might like to have different pages, for eg _About_, _Contact US_ and so on. So it would be sort of a package.json file with one object listing the different entry points for the pages. And then we would go through the files and build them.

**Comment by claytn** [comment]
Agreed. Should we be assuming that all html files lie within the same directory? I think that would be the simplest way at first and later if we wanted to allow for path specification for different sets of modules we could.

**Comment by vritant24** [comment]
That's fair to assume so. Require a folder named `pages` and have all the 'root' html files be in there. The rest is up to the user to structure.
