### ISSUE TITLE
Inspiration from react

### ISSUE THREAD

**Issue by vritant24** [vritant24/cleave-html#3]
What do you think about using react components with no state management. Compiling that into static html files. It would be powerful for development (with variables and such), and efficient in production (not a lot of js). 

Of course it will be more complicated for people with no knowledge of React like libraries or similar frameworks, and I don't know what percent of those even make static websites.

**Comment by claytn** [comment]
This is a good end goal I think, but it sounds like we'll still have to figure out the html inlining portion as a first step. Is this something you want to start from the beginning or something to develop later on?

**Comment by vritant24** [comment]
Well I first thought of purely inlining html files. No templates whatsoever. Literally just an import statement in a comment like that "cleaves" the html file and inserts another in there.

But thinking more, allowing a component based system seems so much more powerful for generating the files, and even for easier dev and more maintainable code bases.
